version: '3'

networks:
    app-net: {}

services:
    web:
        image: 5ndn/nginx:1.11
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - .docker/nginx/default.conf:/etc/nginx/conf.d/vhost.conf
        depends_on:
            - php
            - mysql
            - redis
        networks:
            - app-net
    php:
        build: .docker/php/
        volumes:
            - .:/app
            - .:/usr/share/nginx/html
        ports:
            - 9000:9000
        depends_on:
            - mysql
            - redis
            - memcache
        networks:
            - app-net
        environment:
          REDIS_PASSWORD: ${REDIS_PASSWORD}
    mysql:
        image: mariadb:latest
        ports:
            - 3306:3306
        volumes:
            - .docker/mysql/data:/var/lib/mysql
            - .docker/mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - app-net
    echo:
        image: oanhnn/laravel-echo-server:latest
        depends_on:
            - redis
        ports:
            - 6001:6001
        volumes:
            - .:/app
        links:
            - redis
            - web
        restart: unless-stopped
        environment:
            LARAVEL_ECHO_SERVER_AUTH_HOST: http://web
            LARAVEL_ECHO_SERVER_DEBUG: 'true'
            LARAVEL_ECHO_SERVER_DB: redis
            LARAVEL_ECHO_SERVER_PROTO: http
            LARAVEL_ECHO_SERVER_REDIS_HOST: redis
            LARAVEL_ECHO_SERVER_REDIS_PORT: 6379
            LARAVEL_ECHO_SERVER_REDIS_PREFIX: echo_
            LARAVEL_ECHO_SERVER_REDIS_PASSWORD: ${REDIS_PASSWORD}
            LARAVEL_ECHO_SERVER_REDIS_DB: 0
        networks:
            - app-net
    redis:
        image: redis:latest
        restart: unless-stopped
        volumes:
            - .docker/redis/data:/data
        ports:
            - 6379:6379
        command: redis-server --bind 0.0.0.0 --requirepass Lotus2112
        networks:
            - app-net
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
    memcache:
        image: memcached:latest
        ports:
            - 11211:11211
        networks:
            - app-net
