version: '3.3'

services:
  www:
    image: wyveo/nginx-php-fpm
    ports:
      - "80:80"
    volumes:
      - "../:/usr/share/nginx/html"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      #- "./docker-configure.sh:/usr/local/bin/docker-configure"

  mysql:
    image: "mariadb:latest"
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app"
      - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    volumes:
      - "mysql_data:/var/lib/mysql"

  redis:
    image: "redis:latest"
    command: "redis-server --appendonly yes"
    volumes:
      - "redis_data:/data"

  echo:
    build: ./echo
    ports:
      - "88:80"
    working_dir: "/usr/src/app"
    volumes:
      - "../:/usr/src/app"

volumes:
  app_storage:
  mysql_data:
  redis_data:
